name: rdf-wf-7
channels:
- conda-forge
dependencies:
- python =3.10
- pyscal3 >=3.1.1
- pyscal-rdf =0.0.16
- pyiron_base =0.5.31
- pyiron_atomistics =0.2.62
- pyiron-data
- iprpy-data
- jupyterlab
- panel
- voila
- plotly
- jupyterlab-dash
- sphinxdft >=2.7.0
- sphinxdft-data
- lammps =2023.08.02
- calphy =1.2.12
- nglview
- numpy
- sqsgenerator
- pymatgen
- ipykernel
- ipympl
- ipywidgets
- matplotlib-base =3.8.0
- pydantic >=2.3.0
- randspg
- mpi4py =3.1.4
- pylammpsmpi =0.2.3
- sqlalchemy <2.0.0
- rdflib-sqlalchemy
#- rdflib
#- pyyaml
#- jupyterlab
#- graphviz
#- python-graphviz
#- pyyaml
#- ase 
#- ipycytoscape
#- networkx
#- pandas
#- owlready2
